### ISSUE TITLE
QT GUI?

### ISSUE THREAD

**Issue by ilayshp** [gatgui/SeExprArnold#2]
Hello
What are you thinking about qt gui/widgets for shader?

**Comment by gatgui** [comment]
I fear i don't understand your question. If you're talking about implementing UI in Maya, it has been done recently, just be sure to set the MTOA_TEMPLATES_PATH. I haven't yet set any metadata for Houdini yet, but even if i had, it would be imperfect because i need to link the names and values array sizes and there's no way to do it for now.

Now, if you're talking about straight Qt widgets, i would be interested to hear where you'd use them.
